### ISSUE TITLE
[Feat] Return screen capture of a page

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#202]
**Problem Description**
An image of the page is sometimes useful for vision models. 

**Proposed Feature**
Return a Screenshot of the page for vision models

**Implementation Suggestions**
Having a parameter that allows you to toggle whether to capture an image, that is then returned as a URL path to that image?

**Use Case**
This would be useful when a vision model is more appropriate for a particular task, such as web browsing agents. 

**Additional Context**
Add any other context, such as comparisons with similar features in other products or links to prototypes or mockups.

This is important for GB, who should be notified via slack on completion @calebpeffer

**Comment by nickscamara** [comment]
#207

**Comment by ksbomj** [comment]
Hi @nickscamara,

Thank you for making this feature to work, however I have three questions:
- Is this possible to screenshot the entire page? Maybe with multiple screenshots?
- Is this possible to set response header *content-type* to something else than *text/plain*, because now not all browsers recognize it as an image when you open a link. In Chrome it works, but in Firefox it does not and shows image source.
- Is this possible to configure a custom backend to store images, like something S3 compatible?

Again, thank you for a great product!
