### ISSUE TITLE
[BUG] Readme sites are missing some content in code blocks

### ISSUE THREAD

**Issue by calebpeffer** [mendableai/firecrawl#215]
**Describe the Bug**
On certain Readme docs sites, like https://developers.notion.com/reference/post-page, it doesn't look like the entire contents of a code block is available.

**To Reproduce**
Steps to reproduce the issue:

1. [Go to firecrawl.dev/playground](https://www.firecrawl.dev/playground?url=https%3A%2F%2Fdevelopers.notion.com%2Freference%2Fpost-page&limit=10&excludes=&includes=&mode=scrape&generateImgAltText=false&onlyMainContent=false&fetchPageContent=true&extractionSchema=%7B%22type%22%3A%22object%22%2C%22properties%22%3A%7B%22company_mission%22%3A%7B%22type%22%3A%22string%22%7D%2C%22supports_sso%22%3A%7B%22type%22%3A%22boolean%22%7D%2C%22is_open_source%22%3A%7B%22type%22%3A%22boolean%22%7D%7D%7D&extractionPrompt=Based+on+the+information+on+the+page%2C+extract+the+information+from+the+schema.+&maxDepth=&returnOnlyUrls=false&includeHtml=false&fastMode=false)
2. Notice how the Markdown doesn't contain certain rich text. (shortcut Search ""rich\_text": \[\" with control)

**Expected Behavior**
Should return all content on a page.

**Comment by nickscamara** [comment]
@rafaelsideguide @ericciarla is this fixed?

**Comment by nickscamara** [comment]
Still missing `rich_text` snippet

**Comment by rafaelsideguide** [comment]
@calebpeffer @nickscamara I just tested the url. The problem is that the content within the code snippet loads through a request as you scroll down.

I recorded a loom to show this behavior:
https://www.loom.com/share/2c799fef87d844258ce446c0486431e3?sid=de812223-a0e7-49df-8a3c-e83253a8ca26

A solution would be to find and scroll through all code snippets before scraping readme pages.
