### ISSUE TITLE
Potential issues with nested sitemaps

### ISSUE THREAD

**Issue by nickscamara** [mendableai/firecrawl#477]
It seems like Firecrawl doesn't pick up the developers sitemap on this website:
https://airtable.com/developers/web/api/introduction

**Comment by nickscamara** [comment]
[same on perplexi](https://www.perplexity.ai/hub)

**Comment by rafaelsideguide** [comment]
expected behavior for https://airtable.com/developers/web/api/introduction

1. access baseURL sitemap - https://airtable.com/sitemap.xml
2. gets nested sitemap url - https://airtable.com/wac_sitemap.xml
3. access 1st nested sitemap url - https://airtable.com/wac_sitemap.xml
4. gets 4 nested sitemap urls (https://airtable.com/developers_sitemap.xml, https://airtable.com/main_sitemap.xml, https://airtable.com/marketplace_sitemap.xml, https://airtable.com/templates_sitemap.xml, and https://airtable.com/templates_sitemap.xml)
5. For each of 4 nested sitemap url, access url and get all urls (302 + 59 + 112 + 262 + 2457 =  3192)

**Comment by rafaelsideguide** [comment]
Getting some 403's for perplexity one

![Captura de Tela 2024-08-01 às 18 19 34](https://github.com/user-attachments/assets/9daa9403-7ba6-40af-a7e0-33ff4f6df29b)
