### ISSUE TITLE
[Clarification] Playwright Typescript

### ISSUE THREAD

**Issue by djav1985** [mendableai/firecrawl#636]
I could not find any information that explained Playwright vs Playwright Typescript.

Could you clarify the difference? I mean besides the obvious one is written in typescript.. Is the typescript one faster? Lower recourses? Is there a reason to choose it over the other?

Thank you!

**Comment by nickscamara** [comment]
Good catch @djav1985! Thank you! We will add docs for it soon!

**Comment by rafaelsideguide** [comment]
Hey @djav1985, Playwright and Playwright Typescript have no performance differences; the key difference is that Playwright Typescript offers type safety, which can help catch errors during development and improve code readability. If you're working with a TypeScript codebase or want the benefits of static typing, Playwright Typescript is a great choice. Otherwise, standard Playwright works just fine for JavaScript projects.

Closing for now. Feel free to reopen if you have any other questions.
