### ISSUE TITLE
Sometimes commas are not preserved, and elements of a list get concatenated.

### ISSUE THREAD

**Issue by iuliaturc** [mendableai/firecrawl#658]
I'm scraping https://huggingface.co/docs/transformers/model_doc/mistral

Here's my code:
```
from firecrawl import FirecrawlApp
app = FirecrawlApp(api_key=FIRECRAWL_API_KEY)

def run_firecrawl_scrape(url: str):
    scrape_result = app.scrape_url(url, params={'formats': ['markdown']})
    return scrape_result

sample_url = "https://huggingface.co/docs/transformers/model_doc/mistral"
sample_crawl = run_firecrawl_scrape(sample_url)
print(sample_crawl["markdown"])
```

And i'm seeing that elements in a comma-separated list are unwantedly concatenated. Here's what it looks like on the website:
<img width="941" alt="Screenshot 2024-09-11 at 1 26 47 PM" src="https://github.com/user-attachments/assets/b8fb0a1f-4dc1-498b-8c27-ef3c68a33b6f">

And here's the returned markdown:
<img width="1328" alt="Screenshot 2024-09-11 at 1 27 13 PM" src="https://github.com/user-attachments/assets/4d6660c4-45b2-4cd3-8a8e-c2098cc7cd56">

**Comment by nickscamara** [comment]
Interesting! Seems like a parsing issue. ccing @tomkosm / @rafaelsideguide here to help fix it!

**Comment by rafaelsideguide** [comment]
Hey @iuliaturc! The issue you're seeing happens because the commas aren't actually part of the HTML content. They're added using CSS with a `::before` pseudo-element in the style:

```css
.prose.prose-doc .comma:not(:empty)~.comma:not(:empty):before {
    content: ", ";
}
```
![Captura de Tela 2024-10-03 às 16 18 25](https://github.com/user-attachments/assets/7b36b8d3-7322-498b-9b51-7a21901d3076)

Since the commas are injected by CSS and not part of the raw HTML, they won’t appear in the scraped data. Even if you manually copy and paste the content, you’ll notice the commas won’t appear. That’s why we're unable to capture them in the returned markdown.

I'm closing this issue for now, but let me know if you have any other questions or if there's anything else I can help with!
